database:
  url: {{POSTGRES_URL}}/tradingbotdb
  user: tradingbot
  password: admin123

bot:
  symbol: "BTCUSDC"
  name: criptobo-btcusdc
  core_interval: 30
  amount_to_trade: 10

  strategy:
    type: TARGET
    baseDifference: -0.06
    targetMultiply: 3
    targetPricePercentage: 1.0037
    stagnantMinutes: 120

binance:
  url: {{BINANCE_URL}}
  api_key: {{API_KEY}}
  secret_key: {{SECRET_KEY}}
