database:
  url: {{POSTGRES_URL}}/tradingbotdb
  user: tradingbot
  password: admin123

bot:
  symbol: "BTCUSDC"
  name: leverage-btcusdc
  core_interval: 360
  amount_to_trade: 10

  strategy:
    type: LEVAREGE
    baseDifference: 0.03
    targetMultiply: 1.4
    targetPricePercentage: 0.0012   #next price to buy

binance:
  url: {{BINANCE_URL}}
  api_key: {{API_KEY}}
  secret_key: {{SECRET_KEY}}