database:
  url: {{POSTGRES_URL}}/tradingbotdb
  user: tradingbot
  password: admin123

bot:
  symbol: "BTCUSDC"
  name: leverage-btcusdc-1m-20d
  core_interval: 60
  amount_to_trade: 20

  strategy:
    type: LEVERAGE
    baseDifference: 0.033
    targetMultiply: 1.72
    targetPricePercentage: 0.004   #next price to buy

binance:
  url: {{BINANCE_URL}}
  api_key: {{API_KEY}}
  secret_key: {{SECRET_KEY}}
