database:
  url: {{POSTGRES_URL}}/tradingbotdb
  user: tradingbot
  password: admin123

bot:
  symbol: "BTCUSDC"
  name: leverage-btcusdc-5m-30d
  core_interval: 300
  amount_to_trade: 30

  strategy:
    type: LEVERAGE
    baseDifference: 0.033
    targetMultiply: 2.34
    notBuyZone: 1.1
    targetPricePercentage: 0.004
    sellDifference: 0.28

binance:
  url: {{BINANCE_URL}}
  api_key: {{API_KEY}}
  secret_key: {{SECRET_KEY}}
